"""update some fields

Revision ID: 0720756941da
Revises: 0e52ff1f5515
Create Date: 2025-06-16 15:29:46.193173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0720756941da'
down_revision: Union[str, None] = '0e52ff1f5515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tb_user', 'tb_role', ['role_id'], ['role_id'])
    op.drop_column('tb_user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user', sa.Column('role', mysql.VARCHAR(length=10), nullable=False))
    op.drop_constraint(None, 'tb_user', type_='foreignkey')
    op.drop_column('tb_user', 'role_id')
    # ### end Alembic commands ###
