"""last modify models

Revision ID: 1c598434c9e1
Revises: 1369b6c440d5
Create Date: 2025-06-10 14:57:14.608605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c598434c9e1'
down_revision: Union[str, None] = '1369b6c440d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_deal', sa.Column('reason', sa.String(length=255), nullable=True))
    op.add_column('tb_order', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('tb_order', sa.Column('reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_order', 'reason')
    op.drop_column('tb_order', 'description')
    op.drop_column('tb_deal', 'reason')
    # ### end Alembic commands ###
