"""change des name

Revision ID: 2721bcf16059
Revises: 3e14c1023dab
Create Date: 2025-06-23 10:44:17.544668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2721bcf16059'
down_revision: Union[str, None] = '3e14c1023dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_activity_log', sa.Column('activity_description', sa.String(length=255), nullable=True))
    op.drop_column('tb_activity_log', 'description')
    op.add_column('tb_category', sa.Column('category_description', sa.String(length=255), nullable=True))
    op.drop_column('tb_category', 'description')
    op.add_column('tb_deal', sa.Column('deal_description', sa.String(length=255), nullable=True))
    op.drop_column('tb_deal', 'description')
    op.add_column('tb_order', sa.Column('order_description', sa.String(length=255), nullable=True))
    op.drop_column('tb_order', 'description')
    op.add_column('tb_permission', sa.Column('permission_description', sa.String(length=255), nullable=True))
    op.drop_column('tb_permission', 'description')
    op.add_column('tb_permission_type', sa.Column('permission_type_description', sa.String(length=255), nullable=True))
    op.drop_column('tb_permission_type', 'description')
    op.add_column('tb_product', sa.Column('product_description', sa.String(length=255), nullable=True))
    op.drop_column('tb_product', 'description')
    op.add_column('tb_role', sa.Column('role_description', sa.String(length=255), nullable=True))
    op.drop_column('tb_role', 'description')
    op.add_column('tb_type', sa.Column('type_description', sa.String(length=255), nullable=True))
    op.drop_column('tb_type', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_type', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('tb_type', 'type_description')
    op.add_column('tb_role', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('tb_role', 'role_description')
    op.add_column('tb_product', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('tb_product', 'product_description')
    op.add_column('tb_permission_type', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('tb_permission_type', 'permission_type_description')
    op.add_column('tb_permission', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('tb_permission', 'permission_description')
    op.add_column('tb_order', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('tb_order', 'order_description')
    op.add_column('tb_deal', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('tb_deal', 'deal_description')
    op.add_column('tb_category', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('tb_category', 'category_description')
    op.add_column('tb_activity_log', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('tb_activity_log', 'activity_description')
    # ### end Alembic commands ###
