"""cc

Revision ID: 3401d43508ca
Revises: ae415882433d
Create Date: 2025-06-27 11:20:01.661365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3401d43508ca'
down_revision: Union[str, None] = 'ae415882433d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tb_order_details_ibfk_1', 'tb_order_details', type_='foreignkey')
    op.create_foreign_key(None, 'tb_order_details', 'tb_order', ['order_id'], ['order_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_order_details', type_='foreignkey')
    op.create_foreign_key('tb_order_details_ibfk_1', 'tb_order_details', 'tb_order', ['order_id'], ['order_id'])
    # ### end Alembic commands ###
