"""revise database

Revision ID: 3d0dac3f08a7
Revises: 3401d43508ca
Create Date: 2025-07-03 11:03:28.815962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0dac3f08a7'
down_revision: Union[str, None] = '3401d43508ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_order', sa.Column('original_cost', sa.Float(), nullable=False))
    op.add_column('tb_order_details', sa.Column('original_cost_detail', sa.Float(), nullable=False))
    op.add_column('tb_product', sa.Column('original_cost', sa.Float(), nullable=False))
    op.drop_index('product_name', table_name='tb_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('product_name', 'tb_product', ['product_name'], unique=True)
    op.drop_column('tb_product', 'original_cost')
    op.drop_column('tb_order_details', 'original_cost_detail')
    op.drop_column('tb_order', 'original_cost')
    # ### end Alembic commands ###
