"""revise

Revision ID: 3f690bd979ef
Revises: 10da40308fa8
Create Date: 2025-06-24 16:32:32.257264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f690bd979ef'
down_revision: Union[str, None] = '10da40308fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tb_activity_log_ibfk_1', 'tb_activity_log', type_='foreignkey')
    op.create_foreign_key(None, 'tb_activity_log', 'tb_user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_activity_log', type_='foreignkey')
    op.create_foreign_key('tb_activity_log_ibfk_1', 'tb_activity_log', 'tb_user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
