"""modify some fields

Revision ID: 48ca88de5050
Revises: ee9f585fa627
Create Date: 2025-05-28 16:04:37.213076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ca88de5050'
down_revision: Union[str, None] = 'ee9f585fa627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_product', sa.Column('channel_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_product', 'channel_cost')
    # ### end Alembic commands ###
