""".

Revision ID: 4f5d481c7e11
Revises: 636245633bac
Create Date: 2025-06-24 16:22:56.698952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5d481c7e11'
down_revision: Union[str, None] = '636245633bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tb_order_details_ibfk_2', 'tb_order_details', type_='foreignkey')
    op.create_foreign_key(None, 'tb_order_details', 'tb_product', ['product_id'], ['product_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_order_details', type_='foreignkey')
    op.create_foreign_key('tb_order_details_ibfk_2', 'tb_order_details', 'tb_product', ['product_id'], ['product_id'])
    # ### end Alembic commands ###
