"""modify db

Revision ID: 535675d98f19
Revises: e787af2e1871
Create Date: 2025-06-19 11:18:49.332903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535675d98f19'
down_revision: Union[str, None] = 'e787af2e1871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_activity_log', sa.Column('target_type', sa.String(length=100), nullable=False))
    op.add_column('tb_activity_log', sa.Column('ip', sa.String(length=255), nullable=True))
    op.add_column('tb_activity_log', sa.Column('agent', sa.String(length=255), nullable=True))
    op.add_column('tb_activity_log', sa.Column('localtion', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_activity_log', 'localtion')
    op.drop_column('tb_activity_log', 'agent')
    op.drop_column('tb_activity_log', 'ip')
    op.drop_column('tb_activity_log', 'target_type')
    # ### end Alembic commands ###
