"""update field in order

Revision ID: 56bcc13a5c5b
Revises: eb9739d44c6b
Create Date: 2025-05-22 16:13:57.742085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '56bcc13a5c5b'
down_revision: Union[str, None] = 'eb9739d44c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_order', sa.Column('order_title', sa.String(length=255), nullable=True))
    op.drop_column('tb_order', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_order', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('tb_order', 'order_title')
    # ### end Alembic commands ###
