"""update some fields

Revision ID: 61acf598d4ec
Revises: 48ca88de5050
Create Date: 2025-06-03 15:19:13.633995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61acf598d4ec'
down_revision: Union[str, None] = '48ca88de5050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_order', sa.Column('contact_name', sa.String(length=255), nullable=False))
    op.add_column('tb_order', sa.Column('contact_email', sa.String(length=255), nullable=False))
    op.add_column('tb_order', sa.Column('contact_phone', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_order', 'contact_phone')
    op.drop_column('tb_order', 'contact_email')
    op.drop_column('tb_order', 'contact_name')
    # ### end Alembic commands ###
