""".

Revision ID: 636245633bac
Revises: 03c1fa95cbdd
Create Date: 2025-06-24 16:19:57.221009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636245633bac'
down_revision: Union[str, None] = '03c1fa95cbdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tb_product_ibfk_1', 'tb_product', type_='foreignkey')
    op.create_foreign_key(None, 'tb_product', 'tb_category', ['category_id'], ['category_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_product', type_='foreignkey')
    op.create_foreign_key('tb_product_ibfk_1', 'tb_product', 'tb_category', ['category_id'], ['category_id'])
    # ### end Alembic commands ###
