"""update some fields in order details

Revision ID: 6d134ec8a182
Revises: 56bcc13a5c5b
Create Date: 2025-05-28 14:04:17.556446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6d134ec8a182'
down_revision: Union[str, None] = '56bcc13a5c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_order_details', sa.Column('price_for_customer', sa.Float(), nullable=True))
    op.drop_column('tb_order_details', 'discount_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_order_details', sa.Column('discount_percent', mysql.FLOAT(), nullable=True))
    op.drop_column('tb_order_details', 'price_for_customer')
    # ### end Alembic commands ###
