"""update some wrong fields

Revision ID: 6d27a8f61be4
Revises: e21e69febb7f
Create Date: 2025-05-19 21:15:23.134663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6d27a8f61be4'
down_revision: Union[str, None] = 'e21e69febb7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_order', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tb_order', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('tb_product', sa.Column('maximum_discount_price', sa.Float(), nullable=True))
    op.drop_column('tb_product', 'maximun_discount_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_product', sa.Column('maximun_discount_price', mysql.FLOAT(), nullable=True))
    op.drop_column('tb_product', 'maximum_discount_price')
    op.drop_column('tb_order', 'updated_by')
    op.drop_column('tb_order', 'updated_at')
    # ### end Alembic commands ###
