"""update some fields in orderdetails

Revision ID: 7cbff8b1ebd1
Revises: 6d27a8f61be4
Create Date: 2025-05-20 09:50:08.826821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbff8b1ebd1'
down_revision: Union[str, None] = '6d27a8f61be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_order_details', sa.Column('final_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_order_details', 'final_price')
    # ### end Alembic commands ###
