""".

Revision ID: 8bf5371c9db3
Revises: c775d60896d0
Create Date: 2025-06-24 16:30:40.242479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf5371c9db3'
down_revision: Union[str, None] = 'c775d60896d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tb_user_ibfk_1', 'tb_user', type_='foreignkey')
    op.create_foreign_key(None, 'tb_user', 'tb_role', ['role_id'], ['role_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_user', type_='foreignkey')
    op.create_foreign_key('tb_user_ibfk_1', 'tb_user', 'tb_role', ['role_id'], ['role_id'])
    # ### end Alembic commands ###
