"""change the name of property

Revision ID: 9fc3cb0e3205
Revises: 535675d98f19
Create Date: 2025-06-19 11:42:33.360905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9fc3cb0e3205'
down_revision: Union[str, None] = '535675d98f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_activity_log', sa.Column('location', sa.String(length=255), nullable=True))
    op.drop_column('tb_activity_log', 'localtion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_activity_log', sa.Column('localtion', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('tb_activity_log', 'location')
    # ### end Alembic commands ###
