""".

Revision ID: c775d60896d0
Revises: 4f5d481c7e11
Create Date: 2025-06-24 16:29:42.542048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c775d60896d0'
down_revision: Union[str, None] = '4f5d481c7e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tb_role_permission_ibfk_2', 'tb_role_permission', type_='foreignkey')
    op.create_foreign_key(None, 'tb_role_permission', 'tb_role', ['role_id'], ['role_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_role_permission', type_='foreignkey')
    op.create_foreign_key('tb_role_permission_ibfk_2', 'tb_role_permission', 'tb_role', ['role_id'], ['role_id'])
    # ### end Alembic commands ###
