"""delete product type in product model

Revision ID: e21e69febb7f
Revises: b1f5d89fe8b9
Create Date: 2025-05-19 20:27:11.467597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e21e69febb7f'
down_revision: Union[str, None] = 'b1f5d89fe8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_product', 'product_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_product', sa.Column('product_type', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
