"""modify database

Revision ID: e787af2e1871
Revises: 8a9516129d30
Create Date: 2025-06-18 16:50:33.020909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e787af2e1871'
down_revision: Union[str, None] = '8a9516129d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_product', 'product_role',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               nullable=False)
    op.create_foreign_key(None, 'tb_product', 'tb_role', ['product_role'], ['role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_product', type_='foreignkey')
    op.alter_column('tb_product', 'product_role',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
