"""modify some models

Revision ID: ee9f585fa627
Revises: 6d134ec8a182
Create Date: 2025-05-28 16:00:36.574203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9f585fa627'
down_revision: Union[str, None] = '6d134ec8a182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_order', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('tb_order', sa.Column('billing_address', sa.String(length=255), nullable=True))
    op.add_column('tb_order_details', sa.Column('service_contract_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_order_details', 'service_contract_duration')
    op.drop_column('tb_order', 'billing_address')
    op.drop_column('tb_order', 'address')
    # ### end Alembic commands ###
